import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Box,
  Text,
  Heading,
  Flex,
  Center,
  Stack,
  Container,
} from "@chakra-ui/react";
import Navbar from "../components/Navbar";
import IDL from "../idl/idl.json";
import { Grid, GridItem } from "@chakra-ui/react";
import InstructionForm from "../components/InstructionForm";

const Home: NextPage = () => {
  return (
    <Box bg="gray.50" minH="100vh">
      <Head>
        <title>Anchor UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <Container maxW="container.xl" py={4}>
          <Heading pb={4}>{IDL["name"]}</Heading>
          <Grid templateColumns="repeat(3, 1fr)" gap={6}>
            {IDL["instructions"].map((ix, i) => {
              return (
                <GridItem key={i} w="100%">
                  <InstructionForm
                    ixName={ix["name"]}
                    ixAccounts={ix["accounts"]}
                    ixArgs={ix["args"]}
                  />
                </GridItem>
              );
            })}
          </Grid>
        </Container>
      </Box>
    </Box>
  );
};

export default Home;
