import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box, Text, Heading, Flex, Center, Stack } from "@chakra-ui/react";
import {
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Input,
} from "@chakra-ui/react";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <Box bg="gray.50" minH="100vh">
      <Head>
        <title>Anchor UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <Flex py={8} align="center" justify={"center"} direction="column">
          {/* The Things inside this Box need's to be made iterable iterable  */}
          <Box
            bg="white"
            minW="lg"
            p={8}
            mt={4}
            borderRadius="base"
            boxShadow={"lg"}
          >
            {/* Name of the Ix  */}
            <Heading pb={4}>CreateNFT</Heading>
            <Stack spacing="4">
              <FormControl>
                {/* Each Account Name  */}
                <FormLabel>masterEdition</FormLabel>
                {/* Each Account Input Field */}
                <Input type="text" />
                {/* Error Message Log or helper text for that account */}
                <FormErrorMessage>We never share your email.</FormErrorMessage>
              </FormControl>
              <FormControl>
                <FormLabel>metadataMint</FormLabel>
                <Input type="text" />
                <FormHelperText>isMutable and isSigner</FormHelperText>
              </FormControl>
              <FormControl>
                <FormLabel>updateAuth</FormLabel>
                <Input type="text" />
                <FormHelperText>isMutable and isSigner</FormHelperText>
              </FormControl>
              <FormControl>
                <FormLabel>mplProgram</FormLabel>
                <Input type="text" />
                <FormHelperText>isMutable and isSigner</FormHelperText>
              </FormControl>
            </Stack>
          </Box>
        </Flex>
      </Box>
    </Box>
  );
};

export default Home;
